version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://rohit:rohit123@mysql:3306/mytask
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
          - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mytask
      MYSQL_USER: rohit
      MYSQL_PASSWORD: rohit123 